# Generated by Django 3.2 on 2024-02-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog2', '0002_auto_20240225_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
