# Generated by Django 3.2 on 2024-02-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog2', '0003_alter_post_date_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=120, null=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('body', models.TextField()),
            ],
        ),
    ]
