# Generated by Django 3.2 on 2024-02-25 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog2', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
